In [1]:
%config Completer.use_jedi = False

import os

# os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"   # see issue #152
# os.environ["CUDA_VISIBLE_DEVICES"] = ""

# example of training an conditional gan on the fashion mnist dataset
from numpy import expand_dims
from numpy import zeros
from numpy import ones
import keras
from numpy.random import randn
from numpy.random import randint
from keras.optimizers import Adam
from keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau, LearningRateScheduler
from keras.utils import plot_model
from keras.models import Model
from keras.layers import Input, Reshape, multiply, Embedding, merge, Concatenate, Conv1D, BatchNormalization
from keras.layers import Dense, Flatten, Multiply, LSTM
from keras.layers.advanced_activations import LeakyReLU
import numpy as np
from numpy import asarray
import matplotlib.pyplot as plt
from keras.layers import UpSampling1D
from keras.layers.core import Activation
from keras.layers import Add
import tensorflow as tf
from evaluation_metrics import *
metric_to_calculate = ['FID', 'MMD', 'DTW', 'PC', 'RMSE', 'TWED']
from helper import *
from keras.utils import to_categorical
from keras.callbacks import EarlyStopping, ModelCheckpoint

In [2]:
def reshape(X):
    if len(X.shape) == 1:
        X = X.reshape(X.shape[0], 1)
        return X
    else:
        if X.shape[-1] == 1:
            return X
        else:
            X = X.reshape(X.shape[0], X.shape[1], 1)
            return X

In [3]:
def load_data():
    X_val = reshape(np.load('Data/TrainVal/X_val.npy'))
    y_val = np.load('Data/TrainVal/y_val.npy')

    print (X_val.shape, y_val.shape)
    print (np.unique(y_val, return_counts=True))

    y_val = to_categorical(y_val)
    print (y_val.shape)

    X_test = np.load('Data/Original/test_data.npy')
    y_test = X_test[:,-1]
    X_test = reshape(X_test[:,:-1])

    print (X_test.shape, y_test.shape)
    print (np.unique(y_test, return_counts=True))

    y_test = to_categorical(y_test)
    print (y_test.shape)
    
    return X_val, y_val, X_test, y_test

In [4]:
def load_and_run_model(title, results, BS, EP, Pat, Mon_Term, Mode, X_val, y_val, X_test, y_test):
#     WINDOW_SIZE = 186
#     INPUT_FEAT = 1
#     OUTPUT_CLASS = 3
    
    X = reshape(np.load('Data/GAN_GEN/'+ title+'_X.npy'))
    y = np.load('Data/GAN_GEN/'+ title+'_y.npy')
    print (np.unique(y, return_counts=True))
    y = to_categorical(y)
    print (X.shape, y.shape)

#     filename = os.path.join(results,title)
#     if not os.path.exists(str(filename)):
#         os.makedirs(str(filename))

#     model = load_model_train(WINDOW_SIZE,INPUT_FEAT,OUTPUT_CLASS)
#     cb = [keras.callbacks.EarlyStopping(monitor=Mon_Term, patience=Pat, verbose=1, mode=Mode), 
#           ModelCheckpoint(filename+'/check.h5', save_best_only=True, monitor=Mon_Term, mode=Mode, verbose=1)]

#     history = model.fit(X, y, validation_data=(X_val, y_val), batch_size=BS, epochs=EP, callbacks=cb, verbose=1)
#     save_the_model(filename, model)
#     write_history(filename, history.history)
#     plt.figure(figsize=(5.5,3.2))
#     prediction(X_test, y_test, filename, title)

In [5]:
# Mon_Term = 'val_AUC'
# Mode = 'max'

Mon_Term = 'val_loss'
Mode = 'min'

Model_Name = 'GAP_'
def load_model_train(WINDOW_SIZE,INPUT_FEAT,OUTPUT_CLASS):
    return Parallel_GAP(WINDOW_SIZE,INPUT_FEAT,OUTPUT_CLASS)

# results = 'LSTM_'
# def load_model_train(WINDOW_SIZE,INPUT_FEAT,OUTPUT_CLASS):
#     return parallel_NN_LSTM(WINDOW_SIZE,INPUT_FEAT,OUTPUT_CLASS)

results = 'Class_Results_' + Model_Name + Mon_Term
if not os.path.exists(str(results)):
    os.makedirs(str(results))

BS = 256
EP = 100
Pat = 6

X_val, y_val, X_test, y_test = load_data()

(40955, 186, 1) (40955,)
(array([0., 1., 2.]), array([31181,  2358,  7416]))
(40955, 3)
(203187, 186, 1) (203187,)
(array([0., 1., 2.]), array([155008,  12564,  35615]))
(203187, 3)


In [6]:
title = '2053'
load_and_run_model(title, results, BS, EP, Pat, Mon_Term, Mode, X_val, y_val, X_test, y_test)

(array([0., 1., 2.]), array([130681, 130649, 130842]))
(392172, 186, 1) (392172, 3)


In [7]:
title = '2055'
load_and_run_model(title, results, BS, EP, Pat, Mon_Term, Mode, X_val, y_val, X_test, y_test)

(array([0., 1., 2.]), array([130681, 130649, 130842]))
(392172, 186, 1) (392172, 3)


In [8]:
title = '2057'
load_and_run_model(title, results, BS, EP, Pat, Mon_Term, Mode, X_val, y_val, X_test, y_test)

(array([0., 1., 2.]), array([130681, 130649, 130842]))
(392172, 186, 1) (392172, 3)


In [9]:
title = '3011'
load_and_run_model(title, results, BS, EP, Pat, Mon_Term, Mode, X_val, y_val, X_test, y_test)

(array([0., 1., 2.]), array([130681, 130649, 130842]))
(392172, 186, 1) (392172, 3)


In [10]:
title = '4069'
load_and_run_model(title, results, BS, EP, Pat, Mon_Term, Mode, X_val, y_val, X_test, y_test)

(array([0., 1., 2.]), array([130681, 130649, 130842]))
(392172, 186, 1) (392172, 3)


In [11]:
title = '5023'
load_and_run_model(title, results, BS, EP, Pat, Mon_Term, Mode, X_val, y_val, X_test, y_test)

(array([0., 1., 2.]), array([130681, 130649, 130842]))
(392172, 186, 1) (392172, 3)


In [12]:
title = '5025'
load_and_run_model(title, results, BS, EP, Pat, Mon_Term, Mode, X_val, y_val, X_test, y_test)

(array([0., 1., 2.]), array([130681, 130649, 130842]))
(392172, 186, 1) (392172, 3)


In [13]:
title = '6039'
load_and_run_model(title, results, BS, EP, Pat, Mon_Term, Mode, X_val, y_val, X_test, y_test)

(array([0., 1., 2.]), array([130681, 130649, 130842]))
(392172, 186, 1) (392172, 3)


In [14]:
title = '6049'
load_and_run_model(title, results, BS, EP, Pat, Mon_Term, Mode, X_val, y_val, X_test, y_test)

(array([0., 1., 2.]), array([130681, 130649, 130842]))
(392172, 186, 1) (392172, 3)


In [15]:
title = '6063'
load_and_run_model(title, results, BS, EP, Pat, Mon_Term, Mode, X_val, y_val, X_test, y_test)

(array([0., 1., 2.]), array([130681, 130649, 130842]))
(392172, 186, 1) (392172, 3)


In [16]:
title = '7057'
load_and_run_model(title, results, BS, EP, Pat, Mon_Term, Mode, X_val, y_val, X_test, y_test)

(array([0., 1., 2.]), array([130681, 130649, 130842]))
(392172, 186, 1) (392172, 3)


In [17]:
title = '8069'
load_and_run_model(title, results, BS, EP, Pat, Mon_Term, Mode, X_val, y_val, X_test, y_test)

(array([0., 1., 2.]), array([130681, 130649, 130842]))
(392172, 186, 1) (392172, 3)


In [18]:
# title = '2053'
# X = reshape(np.load('Data/GAN_GEN/'+ title+'_X.npy'))
# y = np.load('Data/GAN_GEN/'+ title+'_y.npy')
# print (np.unique(y, return_counts=True))
# y = to_categorical(y)
# print (X.shape, y.shape)

# filename = os.path.join(results,title)
# if not os.path.exists(str(filename)):
#     os.makedirs(str(filename))

# model = load_model_train(WINDOW_SIZE,INPUT_FEAT,OUTPUT_CLASS)
# cb = [keras.callbacks.EarlyStopping(monitor=Mon_Term, patience=Pat, verbose=1, mode=Mode), 
#       ModelCheckpoint(filename+'/check.h5', save_best_only=True, monitor=Mon_Term, mode=Mode, verbose=1)]

# history = model.fit(X, y, validation_data=(X_val, y_val), batch_size=BS, epochs=EP, callbacks=cb, verbose=1)
# save_the_model(filename, model)
# write_history(filename, history.history)
# prediction(X_test, y_test, filename, title)